### ISSUE TITLE
Text not rendering properly

### ISSUE THREAD

**Issue by lrhorer** [VixenLights/Vixen#148]
Believe it or not, I am still trying to get this season's display working, and this is one among many issues with which I still must deal.  I hope someone can look at this quickly.

I just this morning got my sign working, but it has a problem.  When exporting to an FPP sequence (2.6+) all of the text renders twice, instead of just once, and one of the copies is mirrored, making the text pretty much unreadable.  If the text is supposed to scroll onto the sign left to right, for example, then the correct render scrolls from left to right, but the mirror scrolls from right to left.  Graphics (such as snowflakes) seem to render properly.

This was not happening when I tested the sign and software a couple of months ago under an earlier version of Vixen.  I have included an example compressed sequence.

[sign.zip](https://github.com/VixenLights/Vixen/files/4005584/sign.zip)

**Comment by jeffu231** [comment]
This is likely a setup issue. So lets start with just Vixen. Does it look correct in the Vixen preview when you play it there? Have you tested this by playing the sequence in Vixen directly out to the sign vs exporting to FPP. The goal here is to take the export out of question and determine if the setup issue is in Vixen or FPP.  Unfortunately the file you attached will not help me with determining the issue, so we need to work though these steps.

**Comment by lrhorer** [comment]
It displays correctly in the preview.  I attempted to transmit directly to the controller, but the attempt failed.  I am not entirely certain why.  The 4 controllers are Falcon F16V4 hosts on a different subnet than the host running Vixen.  The main subnet (192.168.1/24) is routed to the show subnet (192.168.8/24) by the Raspberry Pi which runs FPP.  There is of course a static route defined in the routing table of the host which runs Vixen, and the controllers are all visible to the host.

I disabled the "Always transmit channel data" feature in FPP, and as expected the packet count on the F16 controllers stopped incrementing.  I then enabled the IP of the Streaming ACN target in Vixen.  Note I also attempted to enable the other three ACN targets, but this fails with Vixen complaining: "Universe 1 already exists on another controller transmitting to the same device or network. Please configure a different universe to prevent hardware errors."  There is no option for a unicast target, which explains the error, but I would expect it should still work to transmit only to the single target.  When I play a sequence, the packet count on the target host does not increase.  I am unsure how to proceed.

**Comment by lrhorer** [comment]
Oh, pfft.  Of course the attempt to transmit to the controllers fails.  Vixen is broadcasting an Ethernet broadcast, which cannot cross subnet boundaries.  The only way it would ever work is to create a Layer 3 unicast address, which does not look to be possible in Vixen.  Putting the F16 controller on the same physical network as the Vixen host would be a significant chore.

**Comment by jeffu231** [comment]
IF the preview is right, then it likely is something in the patching. I am pretty confident the export to FPP works correctly as there are many of us that our shows running off it. So it has to be configuration somehow. It is a good practice not to reuse universes which is why Vixen tries to enforce that concept. But if you leave the other controllers in multicast and turned off, and can get the one controller set to an IP address, then it should work for that controller. Setting the controller to a specific IP address implies unicast and should cross subnets as long as there are routes between them. I assume you can open the controller config pages in a browser on the Vixen computer and ping them to verify your routing works? You can look in the logs under the My Documents\Vixen 3\logs folder and see if there are any clues in there. You can zip that folder up and attach it. I can look and see if it has anything to help.

**Comment by jeffu231** [comment]
If you set the ip address of the controller in the Vixen controller as the destination, it will be sent as a unicast UDP packet which has a IP destination and should route across the subnets with correct routing. It should not be broadcasting. I have various parts of my show segregated on multiple vLans here and have no issue with it routing across them when in unicast. Setting it to Multicast, will not cross the subnets without some extra magic because that is being broadcast on the computers interface network.

**Comment by lrhorer** [comment]
I recognize that, but I don't see a way to set the IP address in Vixen.

**Comment by jeffu231** [comment]
Select the controller in Vixen and use the gear icon to open the setup where the universes are configured. At the bottom to the right of destination, hit the green plus button. Enter the ip or hostname of the controller. That will add it as a destination that can be selected in the drop down then.

**Comment by lrhorer** [comment]
OK, yeah, I found that, but it won't let me set the interface.

**Comment by lrhorer** [comment]
Goi8ng direct from the Vixen host, the text is still being doubled and mirrored.

**Comment by jeffu231** [comment]
Ok, good. Then it appears the export to FPP is just exporting the problem that is occurring in Vixen itself. If the preview looks correct, then the problem is likely in the patching of the elements to the controller in some way. If you want to zip up the entire profile folder, and give me a dropbox style link to it, I can review the setup and see if I can figure out what is causing the issue. The profile is typically the My Documents\Vixen 3 folder if you are not using multiple profiles.

**Comment by lrhorer** [comment]
I have set up an sftp directory for you at fletchergeek.homelinux.net, UID jeffu231, PID vixen.  There is a file in the jeffu231 directory named vixen_setup.zip.

**Comment by jeffu231** [comment]
I was able to download the profile and take a look at it. I do not see anything in the configuration that looks incorrect. I did some sampling of export data based on where I placed a simple set level effects and the correct channel data comes out where it should be. So the next step is to look at the controller setup with respect to how it is wired. Can you provide a screenshot of the Falcon controller config and describe how the sign is wired and which ports are being used?

**Comment by lrhorer** [comment]
Oops!  I just realized the problem.  How utterly stupid of me!  Pfft.  In order to make the design compact and physically simple, I created a PC Board that attached to the strips at each end of the sign  The boards supply ground one one side and V+ on the other.  They route the signal from each string to the string above it at the end of the string.  This means, however, that the signal passes from left to right on the odd numbered strings and right to left on the even numbered strings.  In all my haste, I neglected to create a zig-zag configuration on the controller.  I am so embarased.  It's bad enough I forgot to make the simple configuration change, but it should have occurred to me immediately what was happening.  I am so very sorry to have wasted your time.  I am going to go hit myself repeatedly with a dumb-ass stick.  Please have a happy holiday despite my needlessly annoying you.

**Comment by jeffu231** [comment]
I suspected you had a zig zag issue and that is where I was headed. Glad you figured it out. No worries on the time. Happy to try and help any time.

**Comment by lrhorer** [comment]
You are most generous.  Thank you.  I am closing the issue.
